# Generated by Django 5.0.4 on 2024-11-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="verification_code",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="verification_code_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
