# Generated by Django 5.0.4 on 2024-11-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_client_verification_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
