# Generated by Django 5.0.4 on 2024-11-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_shippingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="is manager"),
        ),
    ]
