# Generated by Django 5.0.4 on 2024-10-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productimage_productreview_productspecification"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="fr_name",
            field=models.CharField(default="eee", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
