# Generated by Django 5.0.4 on 2024-11-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_category_fr_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="images/products/"),
        ),
    ]
